### ISSUE TITLE
MDSR not working

### ISSUE THREAD

**Issue by owang** [LimBee/NTIRE2017#11]
Hi, I am having some trouble running the demos. if I run 

`th test.lua -model EDSR_x2 -selfEnsemble false
`

it works fine, but then when I run 

`th test.lua -model MDSR -scale 2 -selfEnsemble false`

I get this error:
```
Model: [MDSR]
This is a multi-scale model! Swap the model
/opt/torch/install/bin/luajit: test.lua:64: attempt to index a nil value
stack traceback:
	test.lua:64: in function 'swap'
	test.lua:222: in main chunk
	[C]: in function 'dofile'
	/opt/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
```

or if I run 

`th test.lua -model EDSR_x4 -selfEnsemble false`

I get this error:

```
Model: [EDSR_x4]
>> [1/3]	2276523950_e06e9065b2_z.jpg	/opt/torch/install/bin/luajit: /NTIRE2017/code/utils.lua:313: bad argument #1 to 'copy' (sizes do not match at /opt/torch/extra/cutorch/lib/THC/THCTensorCopy.cu:31)
stack traceback:
	[C]: in function 'copy'
	/NTIRE2017/code/utils.lua:313: in function 'chopForward'
	/NTIRE2017/code/utils.lua:320: in function 'chopForward'
	test.lua:252: in main chunk
	[C]: in function 'dofile'
	/opt/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
```

Any idea what I am doing wrong? Thanks!

**Comment by sanghyun-son** [comment]
Hi.

Maybe there was a mistake when we re-named the model.
We will re-upload the model as soon as possible.

Please check
https://drive.google.com/open?id=0B_riD-4WK4WwOE9PV0RfN3M2QXM
to download the right MDSR before we fix the link.

Also, for the EDSR scale 4 model, would you send us your test images?

We will check the error and fix it.

Thank you.

**Comment by owang** [comment]
Thanks, the new model works great!

For EDSRx4, it happens on any image I tried. For example, this one from your webpage: https://github.com/LimBee/NTIRE2017/blob/master/figs/result/result_1.jpg

**Comment by sanghyun-son** [comment]
Oh, to run the EDSR / MDSR with scale, you have to specify it with -scale argument.
(Because default scale is 2)

For example,
``th test.lua -model EDSR_x4 -scale 4 -selfEnsemble false``
