### ISSUE TITLE
About Discriminator Network

### ISSUE THREAD

**Issue by SummerTrains** [LimBee/NTIRE2017#16]
Did you modify the Discriminator Network of SRResNet ! Thanks!

**Comment by limbee** [comment]
Are you referring to the code in the feature/SRGAN branch? The discriminator network structure is made the same as the structure shown in the original SRGAN paper. 

Our models, EDSR and MDSR, have a different structure than SRResNet.

**Comment by SummerTrains** [comment]
@LimBee Thanks!
