### ISSUE TITLE
Cannot test for scale x3 and x4, utils.lua:313: bad argument #1 to 'copy' (sizes do not match

### ISSUE THREAD

**Issue by yulunzhang** [LimBee/NTIRE2017#18]
Dear all,
I have encountered the issue that I cannot test for scale x3 and x4. But it's ok for scale x2. 
The error message is as follows:
th test.lua -model EDSR_x3 -selfEnsemble false
Preparing dataset...	
[Load time] 0.035s (average 0.017s)
	
Model: [EDSR_x3]	
>> [1/2]	0901x3.png	/home/yulun/torch/install/bin/luajit: .../NTIRE2017/code/utils.lua:313: bad argument #1 to 'copy' (sizes do not match at /home/yulun/torch/extra/cutorch/lib/THC/THCTensorCopy.cu:31)
stack traceback:
	[C]: in function 'copy'
	...yulun/Disk6T/papers/CVPR17EDSR/NTIRE2017/code/utils.lua:313: in function 'chopForward'
	...yulun/Disk6T/papers/CVPR17EDSR/NTIRE2017/code/utils.lua:320: in function 'chopForward'
	test.lua:235: in main chunk
	[C]: in function 'dofile'
	...ulun/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406620

**Comment by limbee** [comment]
The error has occurred because the scale option was not given.
Please give the option '-scale 3'.

**Comment by yulunzhang** [comment]
Thank you! It works.
