### ISSUE TITLE
Asking for the model(challenge&paper)(Links seem to be broken)

### ISSUE THREAD

**Issue by babaozhouy5** [LimBee/NTIRE2017#23]
It sames that the two [links1](http://cv.snu.ac.kr/research/EDSR/model_paper.tar) and [links2](http://cv.snu.ac.kr/research/EDSR/model_challenge.tar) of downloading trained models given in the repo have broken down, I can't download them. Could anybody provide me a backup version? 

Thanks a lot :).

**Edit:** And if possible, could you please also provide the DIV2K datasets download links, i can't download it too.
Thank you very much!

**Comment by limbee** [comment]
Sorry, our server is under repair.
Here is the alternative google drive link for downloading EDSR and MDSR models:
https://drive.google.com/drive/folders/0B3AjYlPQo4LLSkNDZUo4akRhXzQ?usp=sharing

I tried to upload the DIV2K dataset too, but it failed. It would be better to look for official routes or other mirrors.

Thanks!

**Comment by babaozhouy5** [comment]
Thank you so much! It works! ：)
It doesn't matter,  I will try to find another way to download dataset.
Thanks a lot!
