### ISSUE TITLE
about PSNR and SSIM on unknown track

### ISSUE THREAD

**Issue by ZJiaQi** [LimBee/NTIRE2017#24]
Hi~Thanks for your superior works. I want to know  the PSNR and SSIM that you achvevd on the unknown track of DIV2K dataset. Thank you.

**Comment by limbee** [comment]
Sorry, we don't have any results on the unknown track in the paper.
There's a detailed report on the NTIRE2017 Challenge (http://ieeexplore.ieee.org/abstract/document/8014883/) in which you can find our challenge scores, but models submitted to the challenge has slightly different specifications from those for the paper.
However, you can make your own results using our code. Training options should be: -degrade unknown -augUnkDIV2K false. When testing, do not enable the -selfEnsemble option. Follow all the other steps as same as in the bicubic scenario. The final Matlab evaluation code will give you the PSNR and SSIM.

As soon as possible, we'll update our arxiv paper and README to include the results of unknown track.

**Comment by ZJiaQi** [comment]
Thanks for your kind reply.
