### ISSUE TITLE
where can I get Flickr2K dataset?

### ISSUE THREAD

**Issue by wjuny** [LimBee/NTIRE2017#25]
Hi, LimBee,
  I want to get Flickr2K dataset but I can not find this dataset now.

**Comment by limbee** [comment]
Check out this link: http://cv.snu.ac.kr/research/EDSR/Flickr2K.tar
The usage is described in the README > Dataset section.

**Comment by pzz2011** [comment]
It seems that I can not access this link http://cv.snu.ac.kr/research/EDSR/Flickr2K.tar

**Comment by pzz2011** [comment]
thanks, I can get it now. on going:-) 
It's a little big :-)

**Comment by woshidaerduotu99** [comment]
Hello, LimBee！
 I want to download Flickr2K dataset. But the url you gave is no longer valid.
Is there a new website？

**Comment by sanghyun-son** [comment]
You can download it with [this link](https://cv.snu.ac.kr/research/EDSR/Flickr2K.tar)!

Sorry for your inconvenience.

**Comment by xeparc** [comment]
Both links are invalid now
