### ISSUE TITLE
About  Training Time and Gpu 

### ISSUE THREAD

**Issue by allen-ash** [LimBee/NTIRE2017#28]
Hi LimBee, I already learned that you have been  trained several days. Can you tell me which type of Gpu are you using and how many of them? Cause I have only one single Nvidia 1080.

**Comment by limbee** [comment]
The training takes 4 days with single Titan X (Pascal arch). The models will not fit into the memory of 1080 or 1080Ti.

**Comment by allen-ash** [comment]
@LimBee Thanks for the reply, appreciated.
