### ISSUE TITLE
where are the all models

### ISSUE THREAD

**Issue by realbns2008** [LimBee/NTIRE2017#3]
HI, i'm very interested in your works.
I want to try your models for some little project.
But look into your models dir, there aren't any model.
Can you provide the trained models ?
Thanks :)

**Comment by limbee** [comment]
We have uploaded all trained models to our server.
The models submitted to the challenge are located at http://cv.snu.ac.kr/research/EDSR/model_challenge.tar
And the models trained for our paper are located at http://cv.snu.ac.kr/research/EDSR/model_paper.tar

**Comment by realbns2008** [comment]
wow, thanks a lot :)
