### ISSUE TITLE
Can I combine it with GAN?

### ISSUE THREAD

**Issue by Jean332** [LimBee/NTIRE2017#31]
Hello,LimBee,I just read your paper,the result is really cool,and EDSR gets the highest score in PSNR,but it seems it still  has a sense of blurr in vision.I noted that you changed the loss function from l2 to l1,(though I don't know why it's better) As the "SRGAN" paper said:With a high PSNR,the results are often over smoothed,lack high-frequency detail,making them perceptually unsatisfying. And I want to change the l1 loss into perceptually loss, (combine EDSR  with GAN),or using EDSR instead of SRResNet  in SRGAN,will it be better ?

**Comment by limbee** [comment]
I think combining adversarial loss when training a feedforward network is now common in various works. As you said, higher PSNR does not necessarily correspond to better perception. I agree that using GAN idea can result in more pleasing images.

**Comment by Jean332** [comment]
Aha, Thanks for your answer,I'm a newbie in Deep learning,I'll keep working on it,Thank you very much!
