### ISSUE TITLE
the result on BSD100

### ISSUE THREAD

**Issue by liwanlan** [LimBee/NTIRE2017#34]
Hi~
I want to know why the PSNR and SSIM values on BSD100 when I run the pre-trained code are worse than your published a lot . Thank you.

**Comment by limbee** [comment]
What kind of code did you use for evaluation?

**Comment by liwanlan** [comment]
the PyTorch version of EDSR（×4），the results on Set5 and Set14 are well.

**Comment by limbee** [comment]
Then you can ask @thstkdgus35 about this

**Comment by liwanlan** [comment]
ok, thank you.
