### ISSUE TITLE
why does the inference so slow

### ISSUE THREAD

**Issue by realbns2008** [LimBee/NTIRE2017#5]
hi , i'm using the test.lua script in demo to inference a image.
the model i used is EDSR_x2.t7
the gpu i used is Tesla K80
the image i used is 180x100

i type the following command to run the script:
th test.lua -type test -model EDSR_x2.t7  -dataset img_input -gpuid 3

it tooks about 30 seconds to inference
why is it so slow, is there any problem ?

**Comment by limbee** [comment]
I think it's normal since EDSR_x2 is quite big. When we used the latest Titan X, it also took a lot of time. You can test it faster if you use multiple GPUs with -nGPU option.

**Comment by realbns2008** [comment]
Got it .  Thanks , I will try multiple gpus. :)
