### ISSUE TITLE
which forward is better?

### ISSUE THREAD

**Issue by realbns2008** [LimBee/NTIRE2017#6]
there are 3 forward function defined in code/utils.lua

chopFoward is much faster then recursiveForward

it takes 30 secs to go through recursiveForward.
it only take 1 sec to go through chopFoward.

so does it means the quality of recursiveForward is better than chopForward?

**Comment by limbee** [comment]
recursiveForward is obsolete and is no longer used because it is inefficient compared to chopForward. Using chopForward alone will give you the results you want.

**Comment by realbns2008** [comment]
ok~ thanks :)
